export const CREATE_AFFILIATION_REQUEST = "CREATE_AFFILIATION_REQUEST";
export const CREATE_AFFILIATION_SUCCESS = "CREATE_AFFILIATION_SUCCESS";
export const CREATE_AFFILIATION_FAIL = "CREATE_AFFILIATION_FAIL";
export const CREATE_AFFILIATION_RESET = "CREATE_AFFILIATION_RESET";

export const ALL_AFFILIATION_REQUEST = "ALL_AFFILIATION_REQUEST";
export const ALL_AFFILIATION_SUCCESS = "ALL_AFFILIATION_SUCCESS";
export const ALL_AFFILIATION_FAIL = "ALL_AFFILIATION_FAIL";

export const AFFILIATION_DETAILS_REQUEST = "AFFILIATION_DETAILS_REQUEST";
export const AFFILIATION_DETAILS_SUCCESS = "AFFILIATION_DETAILS_SUCCESS";
export const AFFILIATION_DETAILS_FAIL = "AFFILIATION_DETAILS_FAIL";

export const UPDATE_AFFILIATION_REQUEST = "UPDATE_AFFILIATION_REQUEST";
export const UPDATE_AFFILIATION_SUCCESS = "UPDATE_AFFILIATION_SUCCESS";
export const UPDATE_AFFILIATION_FAIL = "UPDATE_AFFILIATION_FAIL";
export const UPDATE_AFFILIATION_RESET = "UPDATE_AFFILIATION_RESET";

export const DELETE_AFFILIATION_REQUEST = "DELETE_AFFILIATION_REQUEST";
export const DELETE_AFFILIATION_SUCCESS = "DELETE_AFFILIATION_SUCCESS";
export const DELETE_AFFILIATION_FAIL = "DELETE_AFFILIATION_FAIL";
export const DELETE_AFFILIATION_RESET = "DELETE_AFFILIATION_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
