export const CREATE_CALENDER_REQUEST = "CREATE_CALENDER_REQUEST";
export const CREATE_CALENDER_SUCCESS = "CREATE_CALENDER_SUCCESS";
export const CREATE_CALENDER_FAIL = "CREATE_CALENDER_FAIL";
export const CREATE_CALENDER_RESET = "CREATE_CALENDER_RESET";

export const ALL_CALENDER_REQUEST = "ALL_CALENDER_REQUEST";
export const ALL_CALENDER_SUCCESS = "ALL_CALENDER_SUCCESS";
export const ALL_CALENDER_FAIL = "ALL_CALENDER_FAIL";

export const CALENDER_DETAILS_REQUEST = "CALENDER_DETAILS_REQUEST";
export const CALENDER_DETAILS_SUCCESS = "CALENDER_DETAILS_SUCCESS";
export const CALENDER_DETAILS_FAIL = "CALENDER_DETAILS_FAIL";

export const UPDATE_CALENDER_REQUEST = "UPDATE_CALENDER_REQUEST";
export const UPDATE_CALENDER_SUCCESS = "UPDATE_CALENDER_SUCCESS";
export const UPDATE_CALENDER_FAIL = "UPDATE_CALENDER_FAIL";
export const UPDATE_CALENDER_RESET = "UPDATE_CALENDER_RESET";

export const DELETE_CALENDER_REQUEST = "DELETE_CALENDER_REQUEST";
export const DELETE_CALENDER_SUCCESS = "DELETE_CALENDER_SUCCESS";
export const DELETE_CALENDER_FAIL = "DELETE_CALENDER_FAIL";
export const DELETE_CALENDER_RESET = "DELETE_CALENDER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
