export const CAREER_SUBMIT_REQUEST = 'CAREER_SUBMIT_REQUEST';
export const CAREER_SUBMIT_SUCCESS = 'CAREER_SUBMIT_SUCCESS';
export const CAREER_SUBMIT_FAIL = 'CAREER_SUBMIT_FAIL';
export const CAREER_SUBMIT_RESET = 'CAREER_SUBMIT_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';