export const CONTACT_US_REQUEST = "CONTACT_US_REQUEST";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";
export const CONTACT_US_RESET = "CONTACT_US_RESET";


export const CLEAR_ERRORS = "CLEAR_ERRORS";