export const CREATE_CARD_REQUEST = "CREATE_CARD_REQUEST";
export const CREATE_CARD_SUCCESS = "CREATE_CARD_SUCCESS";
export const CREATE_CARD_FAIL = "CREATE_CARD_FAIL";
export const CREATE_CARD_RESET = "CREATE_CARD_RESET";

export const ALL_CARD_REQUEST = "ALL_CARD_REQUEST";
export const ALL_CARD_SUCCESS = "ALL_CARD_SUCCESS";
export const ALL_CARD_FAIL = "ALL_CARD_FAIL";

export const CARD_DETAILS_REQUEST = "CARD_DETAILS_REQUEST";
export const CARD_DETAILS_SUCCESS = "CARD_DETAILS_SUCCESS";
export const CARD_DETAILS_FAIL = "CARD_DETAILS_FAIL";

export const UPDATE_CARD_REQUEST = "UPDATE_CARD_REQUEST";
export const UPDATE_CARD_SUCCESS = "UPDATE_CARD_SUCCESS";
export const UPDATE_CARD_FAIL = "UPDATE_CARD_FAIL";
export const UPDATE_CARD_RESET = "UPDATE_CARD_RESET";

export const DELETE_CARD_REQUEST = "DELETE_CARD_REQUEST";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAIL = "DELETE_CARD_FAIL";
export const DELETE_CARD_RESET = "DELETE_CARD_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
