export const CREATE_SUBJECT_REQUEST = "CREATE_SUBJECT_REQUEST";
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS";
export const CREATE_SUBJECT_FAIL = "CREATE_SUBJECT_FAIL";
export const CREATE_SUBJECT_RESET = "CREATE_SUBJECT_RESET";

export const ALL_SUBJECT_REQUEST = "ALL_SUBJECT_REQUEST";
export const ALL_SUBJECT_SUCCESS = "ALL_SUBJECT_SUCCESS";
export const ALL_SUBJECT_FAIL = "ALL_SUBJECT_FAIL";

export const SUBJECT_DETAILS_REQUEST = "SUBJECT_DETAILS_REQUEST";
export const SUBJECT_DETAILS_SUCCESS = "SUBJECT_DETAILS_SUCCESS";
export const SUBJECT_DETAILS_FAIL = "SUBJECT_DETAILS_FAIL";


export const UPDATE_SUBJECT_REQUEST = "UPDATE_SUBJECT_REQUEST";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_FAIL = "UPDATE_SUBJECT_FAIL";
export const UPDATE_SUBJECT_RESET = "UPDATE_SUBJECT_RESET";

export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL";
export const DELETE_SUBJECT_RESET = "DELETE_SUBJECT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS"