export const CREATE_TEACHER_REQUEST = "CREATE_TEACHER_REQUEST";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FAIL = "CREATE_TEACHER_FAIL";
export const CREATE_TEACHER_RESET = "CREATE_TEACHER_RESET";

export const ALL_TEACHER_REQUEST = "ALL_TEACHER_REQUEST";
export const ALL_TEACHER_SUCCESS = "ALL_TEACHER_SUCCESS";
export const ALL_TEACHER_FAIL = "ALL_TEACHER_FAIL";

export const TEACHER_DETAILS_REQUEST = "TEACHER_DETAILS_REQUEST";
export const TEACHER_DETAILS_SUCCESS = "TEACHER_DETAILS_SUCCESS";
export const TEACHER_DETAILS_FAIL = "TEACHER_DETAILS_FAIL";

export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FAIL = "UPDATE_TEACHER_FAIL";
export const UPDATE_TEACHER_RESET = "UPDATE_TEACHER_RESET";

export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FAIL = "DELETE_TEACHER_FAIL";
export const DELETE_TEACHER_RESET = "DELETE_TEACHER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
