export const CREATE_PARTNER_REQUEST = "CREATE_PARTNER_REQUEST";
export const CREATE_PARTNER_SUCCESS = "CREATE_PARTNER_SUCCESS";
export const CREATE_PARTNER_FAIL = "CREATE_PARTNER_FAIL";
export const CREATE_PARTNER_RESET = "CREATE_PARTNER_RESET";

export const ALL_PARTNER_REQUEST = "ALL_PARTNER_REQUEST";
export const ALL_PARTNER_SUCCESS = "ALL_PARTNER_SUCCESS";
export const ALL_PARTNER_FAIL = "ALL_PARTNER_FAIL";

export const PARTNER_DETAILS_REQUEST = "PARTNER_DETAILS_REQUEST";
export const PARTNER_DETAILS_SUCCESS = "PARTNER_DETAILS_SUCCESS";
export const PARTNER_DETAILS_FAIL = "PARTNER_DETAILS_FAIL";

export const UPDATE_PARTNER_REQUEST = "UPDATE_PARTNER_REQUEST";
export const UPDATE_PARTNER_SUCCESS = "UPDATE_PARTNER_SUCCESS";
export const UPDATE_PARTNER_FAIL = "UPDATE_PARTNER_FAIL";
export const UPDATE_PARTNER_RESET = "UPDATE_PARTNER_RESET";

export const DELETE_PARTNER_REQUEST = "DELETE_PARTNER_REQUEST";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_FAIL = "DELETE_PARTNER_FAIL";
export const DELETE_PARTNER_RESET = "DELETE_PARTNER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
